server:
  port: 8083

spring:
  application:
    name: sequence-generator

  datasource:
    url: jdbc:mysql://localhost:3306/yourbank_sequence_generator
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

